export const actionTypes = <const>{
  GET_USER_DATA_REQUEST: 'GET_USER_DATA_REQUEST',
  GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_FAILURE: 'GET_USER_DATA_FAILURE',
  GET_TOKEN_FROM_ASYNC_STORAGE_REQUEST: 'GET_TOKEN_FROM_ASYNC_STORAGE_REQUEST',
  GET_TOKEN_FROM_ASYNC_STORAGE_SUCCESS: 'GET_TOKEN_FROM_ASYNC_STORAGE_SUCCESS',
  GET_TOKEN_FROM_ASYNC_STORAGE_FAILURE: 'GET_TOKEN_FROM_ASYNC_STORAGE_FAILURE',
  CREATE_SHOP_REQUEST: 'CREATE_SHOP_REQUEST',
  CREATE_SHOP_SUCCESS: 'CREATE_SHOP_SUCCESS',
  CREATE_SHOP_FAILURE: 'CREATE_SHOP_FAILURE',
  GET_SHOP_DETAILS_REQUEST: 'GET_SHOP_DETAILS_REQUEST',
  GET_SHOP_DETAILS_SUCCESS: 'GET_SHOP_DETAILS_SUCCESS',
  GET_SHOP_DETAILS_FAILURE: 'GET_SHOP_DETAILS_FAILURE',
};
